# Authoritative structure: Carol's per-file listing (left column of the sheet).
# Names are as she wrote them, with clear typos corrected — see TYPO_FIXES.
FILES = {
 1: ["Ako", "Ambassador Hotel", "An Inspector Calls", "Beachcroft (1967)",
     "Beis Din Guideline of Kashrus & Various Food Ingredients", "Beis Din Review",
     "BestFoods / Unilever", "Biotechnology and Kashrus", "Blooms", "Bugs"],
 2: ["Carmine", "Carmelli", "Cheese", "Chestnuts", "Cigarettes – Cigars",
     "Chief Rabbinate", "Conjoint Relating to Pesach 1988–2002"],
 3: ["Dayan Lerner", "El Al"],
 4: ["Factory Visits Review (Certification Process Project)", "Gelatine Project",
     "Spielsinger & Abraham / Wagner / Kinloss", "Kavana"],
 5: ["Hillel House", "Hindquarters", "Holland", "Honey", "Innocent Drinks", "Israel",
     "Isinglass", "Kashrus Commission", "Kashrus for the Community",
     "Kashrus List (Confectionary) 1962", "Marriage", "Marmite"],
 6: ["Halacha Files", "Magazine Articles", "Newspaper Articles"],
 7: ["Marketing", "MBD", "Medicines", "Misc", "Milk", "Norwood Ravenswood",
     "Overview of Kashrus Division Procedures (2000)", "Obituaries / Memorial Addresses"],
 8: ["Pesach", "OU"],
 9: ["Rakusens", "Paris Beis Din", "Shmita", "Shomer Seminar 2002",
     "Various Correspondence", "Whisky Research & Articles AOP", "Wines"],
 10: ["Chief Rabbinate Strasbourg", "Review of Financial Structure of LBD 1994",
      "The White House", "Travel", "Vinegar", "Waxing of Fruit & Veg", "Xanthan Gum",
      "Zhangjiagang Legal"],
 11: ["Sugar – Tate & Lyle – Cube Sugar – Pesach", "Tartaric Acid", "Tomor Margarine",
      "Transactions of the Jewish Historical Society of England",
      "Very Interesting Articles"],
 12: ["Queries / Shaalos", "The Mesorah of Kosher Birds & Animals", "Shellac"],
 13: ["Rabbi Conway Presentation Synopsis & Brief Biography", "Kitnios",
      "Important Papers", "Feasibility of National Kosher UK Certification",
      "Buckingham Palace Goes Kosher", "Kashrus Meeting of the Beis Din",
      "Report on Kashrus & Shechita Activities", "Letters & Kashrus Regulations",
      "Court Cases", "Legal (CER)"],
 14: ["Kashrus / KLBD Review", "Kashrus Certificates", "Kashrus Committee Meetings",
      "Kashrus Financial Issues", "Kashrus Issues", "Kashrus Promotion Campaign",
      "KLBD Articles", "Policy Decisions with Regard to the Kashrus Guide"],
 15: ["Factory Visits"],
 16: ["CDs", "Cassettes", "Photos"],
 17: ["Rabbi Conway's Notebooks"],
 18: ["Rabbi Silver"],
 19: ["Rabbi Silver"],
 20: ["Fish List", "Analysis of Vertebrae Structure"],
 21: ["Scales", "Oils", "British Museum", "Fish Found in Italy",
      "Fish List & Info B – K"],
 22: ["List & Info of Fish L – S"],
 23: ["Newspapers", "Tuna: Rabbinic Material (1)"],
 24: ["Tuna: Scientific Material (2)", "Tuna: Scientific Material (3)"],
 25: ["Miscellaneous including Specimen of Bonito Scales (4)", "Miscellaneous (5)",
      "W. Simon & Sons Tuna Production", "List of Fish (T)",
      "The Fishes & Crustaceans of Cyprus", "Kosher & Non-Kosher Fish by Country"],
 26: ["Tuna: Scientific Names, Classification, Description & Illustrations (6 & 7)",
      "Tuna: Correspondence (8)", "Tuna: Biblical / Talmudical (9)",
      "Tuna: Rabbinical Literature (10)", "Tuna: Nomenclature (11)"],
 27: ["Turbot"],
 28: ["Turbot"],
 29: ["Shechita", "Divrei Torah", "JFS", "Kedassia"],
 30: ["Eruv"],
}

# Sub-lists Carol enumerated inside an entry — indexed so they are findable.
SUBLISTS = {
 "List of Fish (T)": ["Talapia", "Tea-Time Fish Pastes", "Torbay Solex", "Tobis Fish",
                      "Trigger Fish", "Trout", "Turbot", "Tunny"],
 "Kosher & Non-Kosher Fish by Country": [
    "Britain", "Australia", "Belgium", "Caribbean", "Czech Republic & Slovakia",
    "Denmark", "Fiji", "Finland", "France", "Gibraltar", "Greece", "Hawaii",
    "Hong Kong", "Holland", "Italy", "Malta", "Norway", "Peru", "Portugal", "India",
    "Romania", "Russia", "Spain", "South Africa", "Sri Lanka", "Sweden", "Thailand",
    "Turkey", "USA", "Uruguay", "West Indies", "Yugoslavia"],
 "Fish List & Info B – K": ["Billfishes", "Buckling", "Brisling", "Brill", "Bonito",
    "Cod Roe", "Chubs", "Chinchard", "Coley", "Coalfish", "Caviar", "Catfish", "Carp",
    "Cadascura", "Eels", "Flatfish", "Frozen Fish", "Garfish", "Haddock", "John Dory",
    "Kingklip"],
 "List & Info of Fish L – S": ["Ling", "Lumpfish", "Lumpsucker", "Lungfish", "Mackerel",
    "Marlin", "Megrim", "Mock Halibut", "Mullet", "Smooth Oreodori", "Orange Roughy",
    "Plaice", "Pilot Fish", "Rock Salmon", "Saithe", "Sailfish", "Salmon", "Sardines",
    "Scad", "Shibuta", "Skipjack", "Snoek", "Sild", "Sturgeon", "Swordfish"],
 "Court Cases": ["Rosie Ben Shushan", "JFS", "Solinsky – JD Plitnick", "Blooms"],
}

# Where Carol's per-file listing and her A–Z index disagree. The catalogue follows
# the per-file listing; these are surfaced in the document for her to settle.
CONFLICTS = [
 ("Photos", "File 16 in the file listing, File 18 in the index"),
 ("Fish List", "File 20 in the file listing, File 25 in the index"),
 ("List of Fish (T)", "File 25 in the file listing, File 23 in the index"),
 ("The Fishes & Crustaceans of Cyprus", "File 25 in the file listing, File 23 in the index"),
 ("Kosher & Non-Kosher Fish by Country", "File 25 in the file listing, File 23 in the index"),
 ("Wines", "File 9 in both, but the index also carries a separate 'Wine' at File 10"),
]

TYPO_FIXES = [
 ("Biotecnology", "Biotechnology"), ("Uniliver", "Unilever"), ("Magasine", "Magazine"),
 ("Orbituaries / Orbiruaries", "Obituaries"), ("MBDE", "MBD"), ("Wagmer", "Wagner"),
 ("Bukingham", "Buckingham"), ("Cetification / Feasibilty", "Certification / Feasibility"),
 ("Zhangiagang", "Zhangjiagang"), ("Sri Lanca", "Sri Lanka"), ("Urugway", "Uruguay"),
 ("Yugoslavi", "Yugoslavia"), ("Cadascura", "left as written"),
]
